# Generated by Django 4.2.6 on 2023-10-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_purchase',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_purchase'),
        ),
    ]
