version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data_foodgram:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
      
  backend:
    image: olegmusatov/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/backend_static/
      - backend_media:/app/media/

  frontend:
    image: olegmusatov/foodgram_frontend
    volumes:
      - static:/app/result_build/build

  nginx:
    image: olegmusatov/foodgram_gateway
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/app/static/
      - backend_media:/app/media/
