# Generated by Django 4.2.6 on 2023-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_follow_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_following',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscription'),
        ),
    ]
