# Generated by Django 4.2.6 on 2023-10-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный', 'verbose_name_plural': 'Избранное'},
        ),
    ]
