# Generated by Django 4.2.6 on 2023-10-10 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color_code',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#49B64E', help_text='Цвет в HEX', max_length=7, unique=True, verbose_name='Цветовой код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Enter a valid slug.', 'invalid')], verbose_name='Слаг'),
        ),
    ]
