# Generated by Django 4.2.6 on 2023-10-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_tag_color_code_tag_color_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=200, verbose_name='ед. измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
