# Generated by Django 4.2.6 on 2023-10-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_ingredient_units_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
