# Generated by Django 4.2.6 on 2023-10-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_ingredient_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
