# Generated by Django 4.2.6 on 2023-10-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('guest', 'Анонимный пользователь'), ('authorized user', 'Авторизованный пользователь'), ('administrator', 'Aдминистратор')], default='authorized user', verbose_name='Пользовательская роль'),
        ),
    ]
